name: Build Images

on:
  push:
    branches:
    - master
    - multi-arch
    tags:
      - '*'

jobs:
  BuildBase:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: kubespheredev/builder-base
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_SECRETS }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.4.0
      with:
        context: base
        file: base/Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        push: true
        platforms: linux/amd64,linux/arm64

  BuildGo:
    needs: BuildBase
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: kubespheredev/builder-go
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_SECRETS }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.4.0
      with:
        context: go
        file: go/Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        push: true
        platforms: linux/amd64,linux/arm64

  BuildMaven:
    needs: BuildBase
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: kubespheredev/builder-maven
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_SECRETS }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.4.0
      with:
        context: maven
        file: maven/Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        push: true
        platforms: linux/amd64,linux/arm64

  BuildNodeJs:
    needs: BuildBase
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: kubespheredev/builder-nodejs
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_SECRETS }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.4.0
      with:
        context: nodejs
        file: nodejs/Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        push: true
        platforms: linux/amd64,linux/arm64
